package Vista;

import Libro_ABB.ArbolBinario;
import Libro_ABB.ImplementacionABB;
import Libro_ABB.Libro_ABB;
import Libro_ABB.NArbol;
import Modelo.Editorial;
import Modelo.Libros;
import ModeloDAO.EditorialDAO;
import ModeloDAO.LibrosDAO;
import java.awt.BorderLayout;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leslie
 */
public class InsLibro_ABB extends javax.swing.JFrame {
    private ImplementacionABB simulador = new ImplementacionABB();
    public InsLibro_ABB() {
        initComponents();
        this.Inicializar(false);
        mostrarCabecerasLib();
        cargaComboRuc();
        //Centrar 
        this.setLocationRelativeTo(null);
    }
    
    private void Inicializar (boolean enable){
        this.cbxOrdenamientos.setEnabled(enable);
        this.btnBuscar.setEnabled(enable);
        this.btnEliminar1.setEnabled(enable);
        this.btnEliminar2.setEnabled(enable);
        
    }
    //Metodos de libros
    Libros l = new Libros();
    LibrosDAO ld = new LibrosDAO();
    DefaultTableModel modelo3 = new DefaultTableModel();

    public void mostrarCabecerasLib() {
        modelo3.addColumn("Cod_libro");
        modelo3.addColumn("Nom_libro");
        modelo3.addColumn("Stock");
        modelo3.addColumn("Autor");
        modelo3.addColumn("Cod_editorial");
        jTable1.setModel(modelo3);
    }

    public void limpiarCajasLib() {
        txtCod_libro.setText(null);
        txtNom_libro.setText(null);
        txtStock.setText(null);
        txtAutor.setText(null);
    }


    //Metodos editorial
    Editorial et = new Editorial();
    EditorialDAO etd = new EditorialDAO();
    DefaultTableModel modelo2 = new DefaultTableModel();
    public void mostrarTodosEditoriales() {
        ArrayList<Editorial> ved = new ArrayList<>();

        ved = etd.listarTodo();
        for (int i = 0; i < ved.size(); i++) {
            Object[] data = {ved.get(i).getCod_editorial(), ved.get(i).getNom_editorial(),
                ved.get(i).getTelefono()};
            modelo2.addRow(data);
        }
    }
    public void cargaComboRuc() {
        cbxEditorial.removeAllItems();
        cbxEditorial.addItem("Elegir");
        for (Editorial x : etd.lisEdi()) {
            cbxEditorial.addItem(x.getCod_editorial() + "-" + x.getNom_editorial());
        }
    }
    
    private void repintarArbol() {
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame1.getBounds();
        this.jInternalFrame1 = null;
        this.jInternalFrame1 = new JInternalFrame("Representación gráfica", true);
        this.jDesktopPane1.add(this.jInternalFrame1, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame1.setVisible(true);
        this.jInternalFrame1.setBounds(tamaño);
        this.jInternalFrame1.setEnabled(false);
        this.jInternalFrame1.add(this.simulador.getDibujo(), BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbxEditorial = new javax.swing.JComboBox<>();
        txtAutor = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtNom_libro = new javax.swing.JTextField();
        txtCod_libro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar_libro = new javax.swing.JButton();
        cbxOrdenamientos = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        btnSalir_Cola = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar Libros - Arbol Binario");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jLabel9.setText("Codigo libro");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jLabel10.setText("Nombre libro");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jLabel12.setText("Stock");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jLabel11.setText("Autor");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jLabel19.setText("Selec editorial");

        cbxEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEditorialActionPerformed(evt);
            }
        });

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        txtNom_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNom_libroActionPerformed(evt);
            }
        });

        txtCod_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_libroActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregar_libro.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        btnAgregar_libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        btnAgregar_libro.setText("Agregar Libro");
        btnAgregar_libro.setToolTipText("");
        btnAgregar_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_libroActionPerformed(evt);
            }
        });

        cbxOrdenamientos.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        cbxOrdenamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenamientos", "PreOrden", "InOrden", "PosOrden" }));
        cbxOrdenamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOrdenamientosActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar1.setText("Eliminar caso2");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnEliminar2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnEliminar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar2.setText("Eliminar caso1");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        btnSalir_Cola.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnSalir_Cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        btnSalir_Cola.setText("Salir");
        btnSalir_Cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir_ColaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxOrdenamientos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar_libro, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir_Cola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAgregar_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxOrdenamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir_Cola, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setEnabled(false);
        jInternalFrame1.setFocusCycleRoot(false);
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNom_libro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCod_libro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxEditorial, 0, 130, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod_libro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNom_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.getAccessibleContext().setAccessibleParent(jDesktopPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEditorialActionPerformed

    }//GEN-LAST:event_cbxEditorialActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        txtAutor.requestFocus();
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtNom_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNom_libroActionPerformed
        txtStock.requestFocus();
    }//GEN-LAST:event_txtNom_libroActionPerformed

    private void txtCod_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_libroActionPerformed
        txtNom_libro.requestFocus();
    }//GEN-LAST:event_txtCod_libroActionPerformed
    public boolean validarSt(String datos) {
        return datos.matches("[0-9]+");
    }
    private void btnAgregar_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_libroActionPerformed
    String cod_libro = txtCod_libro.getText();
    String nom_libro = txtNom_libro.getText();
    String stock = txtStock.getText();
    String autor = txtAutor.getText();

    if (cod_libro.isEmpty() || nom_libro.isEmpty() || stock.isEmpty() || autor.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacíos.", "Campos Vacíos!!", JOptionPane.WARNING_MESSAGE);
    } else if (!validarSt(stock.trim())) {
        JOptionPane.showMessageDialog(null, "El stock debe ser un número válido.", "Revisar número!!", JOptionPane.ERROR_MESSAGE);
    } else if (cod_libro.length() != 4) {
        JOptionPane.showMessageDialog(null, "El código del libro debe tener exactamente 4 caracteres.", "Verificar COD_LIBRO!!", JOptionPane.ERROR_MESSAGE);
    } else if (ld.validarCol(cod_libro) > 0) {
        JOptionPane.showMessageDialog(null, "El código del libro no puede coincidir con otro código existente.", "Verificar COD_LIBRO!!", JOptionPane.ERROR_MESSAGE);
    } else {
        String cbxEditorial1 = cbxEditorial.getSelectedItem().toString();
        String cbxEditorialv = cbxEditorial1.substring(0, 4);

        // Crear el objeto Libro_ABB solo con el código del libro
        Libro_ABB libro = new Libro_ABB(cod_libro, "", "", "", "");

        // Insertar el libro en el árbol binario de búsqueda
        if (this.simulador.insertar(libro)) {
            JOptionPane.showMessageDialog(null, "El libro se insertó correctamente en el árbol", "Inserción Exitosa", JOptionPane.INFORMATION_MESSAGE); 
            complementos(); // Complementar la interfaz gráfica según necesidad
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo insertar el libro en el árbol", "Error de Inserción", JOptionPane.ERROR_MESSAGE);
        }

        

        // Insertar en la base de datos o donde corresponda
        l.setCod_libro(cod_libro);
        l.setNom_libro(nom_libro);
        l.setStock(stock.trim());
        l.setAutor(autor);
        l.setCod_editorial(cbxEditorialv);
        // Agregar la fila al modelo de la tabla
        Object data[] = {l.getCod_libro(), l.getNom_libro(), l.getStock(), l.getAutor(), l.getCod_editorial()}; // Solo mostramos el código del libro en la tabla
        
        ld.insertar(l);
        modelo3.addRow(data);
        Inicializar(true);
        JOptionPane.showMessageDialog(null, "Se registró correctamente el libro.", "Registro exitoso!!", JOptionPane.INFORMATION_MESSAGE);
        limpiarCajasLib(); // Limpiar campos del formulario después de la inserción
    }
    }//GEN-LAST:event_btnAgregar_libroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cod_libro = txtCod_libro.getText().trim(); // Obtener el código del libro desde el campo de texto

        if (cod_libro.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el código del libro a buscar.", "Registro exitoso!!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar el libro en el árbol usando la instancia de ImplementacionABB
        String mensaje = simulador.buscarElemento(cod_libro);

        // Actualizar el área de texto y mostrar el mensaje
        txtA.append(mensaje + "\n");
        JOptionPane.showMessageDialog(null, mensaje, "Resultado de Búsqueda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        String cod_libro = txtCod_libro.getText().trim(); // Obtener el código del libro desde el campo de texto

        if (cod_libro.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el código del libro a eliminar.", "Código requerido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar si el libro tiene préstamos pendientes
        if (ld.valPRE_libr(cod_libro) > 0) {
            JOptionPane.showMessageDialog(null, "El libro no puede ser eliminado porque tiene préstamos pendientes.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Eliminar el libro del árbol usando la instancia de ImplementacionABB
        String mensaje = simulador.borrar(cod_libro);

        // Eliminar de la tabla y de la base de datos
        for (int i = modelo3.getRowCount() - 1; i >= 0; i--) {
            if (modelo3.getValueAt(i, 0).equals(cod_libro)) {
                modelo3.removeRow(i);
                break; // Suponiendo que solo debe eliminar una fila por código de libro encontrado
            }
        }
        ld.eliminar(cod_libro); // Eliminar de la base de datos

        // Mostrar mensaje de éxito
        txtA.append(mensaje + "\n");
        JOptionPane.showMessageDialog(null, mensaje, "Resultado de Eliminación", JOptionPane.INFORMATION_MESSAGE);

        // Actualizar elementos adicionales según sea necesario
        complementos();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        String cod_libro = txtCod_libro.getText().trim(); // Obtener el código del libro desde el campo de texto

        if (cod_libro.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el código del libro a eliminar.", "Código requerido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar si el libro tiene préstamos pendientes
        if (ld.valPRE_libr(cod_libro) > 0) {
            JOptionPane.showMessageDialog(null, "El libro no puede ser eliminado porque tiene préstamos pendientes.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Eliminar el libro del árbol usando la instancia de ImplementacionABB
        String mensaje = simulador.borrar2(cod_libro);

        // Eliminar de la tabla y de la base de datos
        for (int i = modelo3.getRowCount() - 1; i >= 0; i--) {
            if (modelo3.getValueAt(i, 0).equals(cod_libro)) {
                modelo3.removeRow(i);
                break; // Suponiendo que solo debe eliminar una fila por código de libro encontrado
            }
        }
        ld.eliminar(cod_libro); // Eliminar de la base de datos

        // Mostrar mensaje de éxito
        txtA.append(mensaje + "\n");
        JOptionPane.showMessageDialog(null, mensaje, "Resultado de Eliminación", JOptionPane.INFORMATION_MESSAGE);

        // Actualizar elementos adicionales según sea necesario
        complementos();
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void cbxOrdenamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOrdenamientosActionPerformed
        Object opcion = this.cbxOrdenamientos.getSelectedItem();
        String ordenamiento = null;
        
        if (opcion.equals("InOrden")) {
            txtA.append("InOrden");
            ordenamiento = this.simulador.inOrden();
        }
        if (opcion.equals("PreOrden")) {
            txtA.append("PreOrden");
            ordenamiento = this.simulador.preOrden();
        }
        if (opcion.equals("PosOrden")) {
            txtA.append("PosOrden");
            ordenamiento = this.simulador.PostOrden();
        }
        
        this.txtA.setText("");
        this.txtA.setText(ordenamiento);
    }//GEN-LAST:event_cbxOrdenamientosActionPerformed

    private void btnSalir_ColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir_ColaActionPerformed
        Principal pr = new Principal();
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir_ColaActionPerformed
    public void complementos() {
        this.repintarArbol();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsLibro_ABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsLibro_ABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsLibro_ABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsLibro_ABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsLibro_ABB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar_libro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnSalir_Cola;
    private javax.swing.JComboBox<String> cbxEditorial;
    private javax.swing.JComboBox<String> cbxOrdenamientos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCod_libro;
    private javax.swing.JTextField txtNom_libro;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
