
package Vista;

import Modelo.Encargado;
import ModeloDAO.EncargadoDAO;
import Modelo.Estudiantes;
import ModeloDAO.EstudiantesDAO;
import Modelo.Editorial;
import ModeloDAO.EditorialDAO;
import Modelo.Libros;
import ModeloDAO.LibrosDAO;
import java.awt.event.KeyEvent;  //enter
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Confi.Conexion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tony2
 */
public class LibroExistente extends javax.swing.JFrame {

    /**
     * Creates new form LibroExistente
     */
    public LibroExistente() {
        initComponents();
        //Centrar el LibroExistente
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jblCodLibro = new javax.swing.JLabel();
        txtCl = new javax.swing.JTextField();
        btnAgregarLE = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Virtual -- Agregar Libro Existente");
        setResizable(false);

        jblCodLibro.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jblCodLibro.setText("Cod Libro");
        jblCodLibro.setToolTipText("");

        txtCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClActionPerformed(evt);
            }
        });

        btnAgregarLE.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        btnAgregarLE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnAgregarLE.setText("Agregar Libro");
        btnAgregarLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLEActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jLabel5.setText("Stock");

        jDesktopPane1.setLayer(jblCodLibro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtCl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAgregarLE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnVolver, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btnAgregarLE, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jblCodLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(67, 67, 67))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCl, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtS))
                        .addGap(125, 125, 125))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblCodLibro))
                .addGap(32, 32, 32)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarLE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean validarNF(String datos) {
        return datos.matches("[0-9]+");
    }
    
    
    private void btnAgregarLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLEActionPerformed
        LibrosDAO ld = new LibrosDAO();
        DefaultTableModel modelo3 = new DefaultTableModel();
        String cod_ale = txtCl.getText();
        String cod_sle= txtS.getText();
        if ((cod_ale.equals("")) || (cod_sle.equals(""))){
                JOptionPane.showInternalMessageDialog(null, "Los campos no pueden estar vacios.",
                        "Campos Vacios!!", JOptionPane.WARNING_MESSAGE);
        }else if(!validarNF(cod_sle.trim())){
            JOptionPane.showInternalMessageDialog(null, "Verificar si son números"
                        ,"Revisar numero!!", JOptionPane.ERROR_MESSAGE);
        }else if (cod_ale.length()!=4){
                JOptionPane.showInternalMessageDialog(null, "Verificar si el COD_LIBRO tiene 4 caracteres"
                        ,"Verificar COD_LIBRO!", JOptionPane.ERROR_MESSAGE);
        } else if (ld.validarCol(cod_ale) == 0) {
                JOptionPane.showInternalMessageDialog(null, "El COD_LIBRO no existe"
                ,"Verificar COD_LIBRO!!", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                int cod_slqq= Integer.parseInt(cod_sle);
                Conexion con = new Conexion();
                Connection conn;
                PreparedStatement ps;
                ResultSet rs;
                String sqlSelect = "SELECT stock FROM libros WHERE cod_libro = ?";
                conn = con.getConexion();
                ps = conn.prepareStatement(sqlSelect); 
                ps.setString(1, cod_ale);
                rs = ps.executeQuery();
                        while (rs.next()) {
                        String  cod=null;
                        int stockActual = rs.getInt("stock");
                        int nuevoStock = stockActual + cod_slqq;
                        String sqlUpdate = "UPDATE libros SET stock=? WHERE cod_libro=?";
                        ps = conn.prepareStatement(sqlUpdate);
                        ps.setInt(1, nuevoStock);
                        ps.setString(2, cod_ale);
                        ps.executeUpdate();
                        JOptionPane.showInternalMessageDialog(null, "Se actualizó el Stock del libro.",
                            "Registro exitoso!!", JOptionPane.INFORMATION_MESSAGE);
                        
                    }
            } catch (SQLException | NumberFormatException ex) {
                     Logger.getLogger(LibrosDAO.class.getName()).log(Level.SEVERE, null, ex);

        }     
        
        }
        
        
    }//GEN-LAST:event_btnAgregarLEActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Principal pr=new Principal();
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClActionPerformed
            txtS.requestFocus();
    }//GEN-LAST:event_txtClActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibroExistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibroExistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibroExistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroExistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibroExistente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLE;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jblCodLibro;
    private javax.swing.JTextField txtCl;
    private javax.swing.JTextField txtS;
    // End of variables declaration//GEN-END:variables
}
