/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Grafos.AlgoritmoCaminoLargo;
import Grafos.AlgoritmoDijkstra;
import Grafos.DatosGraficos;
import Grafos.PintanrDibujos;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
/**
 *
 * @author leslie
 */
public class UbicacionGrafos extends javax.swing.JFrame {

     private int Numerotope = 0;//Numero de nodos 
    
    DatosGraficos arboles = new DatosGraficos();

    public static void PintarFiguras(int tope, DatosGraficos arboles) {//pinta lo q esta antes en el panel 
        for (int j = 0; j < tope; j++) {
            for (int k = 0; k < tope; k++) {
                if (arboles.getmAdyacencia(j, k) == 1) {
                    PintanrDibujos.pinta_Linea(jPanel3.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), arboles.getCordeX(k), arboles.getCordeY(k), arboles.getmCoeficiente(j, k));
                }
            }
        }
        for (int j = 0; j < tope; j++) {
            PintanrDibujos.pinta_Circulo(jPanel3.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), arboles.getNombre(j));
        }

    }
    public UbicacionGrafos() {
        initComponents();
        cbxEditorialesDestino.setEnabled(false);
        cbxEditorialesOrigen.setEnabled(false);
        btnCaminoCorto.setEnabled(false);
        btnCaminoLargo.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnMostrarCaminos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxEditorialesDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxEditorialesOrigen = new javax.swing.JComboBox<>();
        btnCaminoCorto = new javax.swing.JButton();
        btnCaminoLargo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imgMapa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(152, 192, 192));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(252, 241, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnMostrarCaminos.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        btnMostrarCaminos.setText("Mostrar Caminos");
        btnMostrarCaminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCaminosActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Origen:");

        cbxEditorialesDestino.setBackground(new java.awt.Color(255, 255, 255));
        cbxEditorialesDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editorial Bruno", "Editorial Escuela Activa", "Editorial San Marcos", "Editorial Delta", "Grupo Editorial Lex & Lurix", "Ediciones Mirbet", "Editorial COREDISE SAC", "Editorial Ingenio" }));
        cbxEditorialesDestino.setAutoscrolls(true);
        cbxEditorialesDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEditorialesDestinoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Destino:");

        cbxEditorialesOrigen.setBackground(new java.awt.Color(255, 255, 255));
        cbxEditorialesOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editorial Bruno", "Editorial Escuela Activa", "Editorial San Marcos", "Editorial Delta", "Grupo Editorial Lex & Lurix", "Ediciones Mirbet", "Editorial COREDISE SAC", "Editorial Ingenio" }));
        cbxEditorialesOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEditorialesOrigenActionPerformed(evt);
            }
        });

        btnCaminoCorto.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selectedButtonForeground"));
        btnCaminoCorto.setText("Buscar camino mas corto");
        btnCaminoCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminoCortoActionPerformed(evt);
            }
        });

        btnCaminoLargo.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selectedButtonForeground"));
        btnCaminoLargo.setText("Buscar camino mas largo");
        btnCaminoLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminoLargoActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Distancia (Km):");

        txtDistancia.setBackground(new java.awt.Color(255, 255, 255));
        txtDistancia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDistancia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnMostrarCaminos, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCaminoCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaminoLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxEditorialesOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEditorialesDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnMostrarCaminos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEditorialesOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEditorialesDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCaminoCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCaminoLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        imgMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapa2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imgMapa)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgMapa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgMapa.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("el Centro Cívico de Lima:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Editoriales ubicadas en");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.getAccessibleContext().setAccessibleName("Editoriales ubicadas en ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarCaminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCaminosActionPerformed
        cbxEditorialesOrigen.setEnabled(true);
        txtDistancia.setEnabled(false);
        jPanel3.paint(jPanel3.getGraphics());
        
        int Matriz[][] = {
          // 1  2  3  4  5  6  7  8
            {0, 1, 0, 1, 1, 0, 0, 0},
            {1, 0, 1, 0, 0, 0, 0, 1},
            {0, 1, 0, 1, 0, 0, 0, 1},
            {1, 0, 1, 0, 1, 1, 0, 0},
            {1, 0, 0, 1, 0, 1, 0, 0},
            {0, 0, 0, 1, 1, 0, 1, 0},
            {0, 0, 0, 0, 0, 1, 0, 1},
            {0, 1, 1, 0, 0, 0, 1, 0}
        };

        double coe[][] = {
          // 1  2  3  4  5  6  7  8
            {0, 0.835, 0, 1.35, 1.62, 0, 0, 0},
            {0.835, 0, 0.672, 0, 0, 0, 0, 1.12},
            {0, 0.672, 0, 0.353, 0, 0, 0, 0.718},
            {1.35, 0, 0.353, 0, 0.397, 0.619, 0, 0},
            {1.62, 0, 0, 0.397, 0, 0.527, 0, 0},
            {0, 0, 0, 0.619, 0.527, 0, 0.145, 0},
            {0, 0, 0, 0, 0, 0.145, 0, 0.904},
            {0, 1.12, 0.718, 0, 0, 0, 0.904, 0}
        };
        //coordenadas de posicion de circulos
        int xx1[] = {84, 270, 558, 632, 769, 886, 920, 649};
        int yy1[] = {665, 368, 364, 490, 592, 397, 342, 69};
        String nom[] = {"1", "2", "3", "4", "5", "6", "7", "8"};
      
        for (int j = 0; j < 8; j++) {
            arboles.setCordeX(j, xx1[j]);
            arboles.setCordeY(j, yy1[j]);
            arboles.setNombre(j, nom[j]);

        }
        for (int j = 0; j < 8; j++) {
            for (int k = 0; k < 8; k++) {
                arboles.setmAdyacencia(j, k, Matriz[j][k]);
                arboles.setmCoeficiente(j, k, coe[j][k]);
            }
        }
        Numerotope = 8;
        PintarFiguras(Numerotope, arboles);
    }//GEN-LAST:event_btnMostrarCaminosActionPerformed

    private void btnCaminoCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminoCortoActionPerformed
        int origen = 0, destino = 0;
        String nombreOrigen, nombreDestino;
        nombreOrigen = (String)cbxEditorialesOrigen.getSelectedItem();
        nombreDestino = (String)cbxEditorialesDestino.getSelectedItem();
        
        if ("Editorial Bruno".equals(nombreOrigen)) {
            origen = 0;
        }
        if ("Editorial Escuela Activa".equals(nombreOrigen)) {
            origen = 1;
        }
        if ("Editorial San Marcos".equals(nombreOrigen)) {
            origen = 2;
        }
        if ("Editorial Delta".equals(nombreOrigen)) {
            origen = 3;
        }
        if ("Grupo Editorial Lex & Lurix".equals(nombreOrigen)) {
            origen = 4;
        }
        if ("Ediciones Mirbet".equals(nombreOrigen)) {
            origen = 5;
        }
        if ("Editorial COREDISE SAC".equals(nombreOrigen)) {
            origen = 6;
        }
        if ("Editorial Ingenio".equals(nombreOrigen)) {
            origen = 7;
        }
       
        if ("Editorial Bruno".equals(nombreDestino)) {
            destino = 0;
        }
        if ("Editorial Escuela Activa".equals(nombreDestino)) {
            destino = 1;
        }
        if ("Editorial San Marcos".equals(nombreDestino)) {
           destino = 2;
        }
        if ("Editorial Delta".equals(nombreDestino)) {
            destino = 3;
        }
        if ("Grupo Editorial Lex & Lurix".equals(nombreDestino)) {
            destino = 4;
        }
        if ("Ediciones Mirbet".equals(nombreDestino)) {
            destino = 5;
        }
        if ("Editorial COREDISE SAC".equals(nombreDestino)) {
            destino = 6;
        }
        if ("Editorial Ingenio".equals(nombreDestino)) {
            destino = 7;
        }
        
        if (origen == destino) {
            Font fuente = new Font("Arial", Font.PLAIN, 14);
            txtDistancia.setFont(fuente);
            JOptionPane.showMessageDialog(null, "Estas en: "+nombreOrigen);
            txtDistancia.setText("Intenta de nuevo...");
            txtDistancia.setEnabled(false);
            txtDistancia.setForeground(Color.RED);
        } else {
            AlgoritmoDijkstra Dijkstra = new AlgoritmoDijkstra(arboles, Numerotope, origen, destino);
            Dijkstra.dijkstra();
            Font fuente = new Font("Arial", Font.PLAIN, 14);
            txtDistancia.setFont(fuente);
            txtDistancia.setText("No hay ningun error :)");
            txtDistancia.setForeground(Color.BLUE);
            txtDistancia.setEnabled(false);
            
            txtDistancia.setText(Dijkstra.getAcumulado() + " KM");
        }
    }//GEN-LAST:event_btnCaminoCortoActionPerformed

    private void cbxEditorialesOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEditorialesOrigenActionPerformed
        cbxEditorialesDestino.setEnabled(true);
    }//GEN-LAST:event_cbxEditorialesOrigenActionPerformed

    private void cbxEditorialesDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEditorialesDestinoActionPerformed
        btnCaminoCorto.setEnabled(true);
        btnCaminoLargo.setEnabled(true);
    }//GEN-LAST:event_cbxEditorialesDestinoActionPerformed

    private void btnCaminoLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminoLargoActionPerformed
        int origen = 0, destino = 0;
        String nombreOrigen, nombreDestino;
        nombreOrigen = (String)cbxEditorialesOrigen.getSelectedItem();
        nombreDestino = (String)cbxEditorialesDestino.getSelectedItem();
        
        if ("Editorial Bruno".equals(nombreOrigen)) {
            origen = 0;
        }
        if ("Editorial Escuela Activa".equals(nombreOrigen)) {
            origen = 1;
        }
        if ("Editorial San Marcos".equals(nombreOrigen)) {
            origen = 2;
        }
        if ("Editorial Delta".equals(nombreOrigen)) {
            origen = 3;
        }
        if ("Grupo Editorial Lex & Lurix".equals(nombreOrigen)) {
            origen = 4;
        }
        if ("Ediciones Mirbet".equals(nombreOrigen)) {
            origen = 5;
        }
        if ("Editorial COREDISE SAC".equals(nombreOrigen)) {
            origen = 6;
        }
        if ("Editorial Ingenio".equals(nombreOrigen)) {
            origen = 7;
        }
       
        if ("Editorial Bruno".equals(nombreDestino)) {
            destino = 0;
        }
        if ("Editorial Escuela Activa".equals(nombreDestino)) {
            destino = 1;
        }
        if ("Editorial San Marcos".equals(nombreDestino)) {
           destino = 2;
        }
        if ("Editorial Delta".equals(nombreDestino)) {
            destino = 3;
        }
        if ("Grupo Editorial Lex & Lurix".equals(nombreDestino)) {
            destino = 4;
        }
        if ("Ediciones Mirbet".equals(nombreDestino)) {
            destino = 5;
        }
        if ("Editorial COREDISE SAC".equals(nombreDestino)) {
            destino = 6;
        }
        if ("Editorial Ingenio".equals(nombreDestino)) {
            destino = 7;
        }
        
        if (origen == destino) {
            Font fuente = new Font("Arial", Font.PLAIN, 14);
            txtDistancia.setFont(fuente);
            JOptionPane.showMessageDialog(null, "Estas en: "+nombreOrigen);
            txtDistancia.setText("Intenta de nuevo...");
            txtDistancia.setEnabled(false);
            txtDistancia.setForeground(Color.RED);
        } else {
            AlgoritmoCaminoLargo caminoLargo = new AlgoritmoCaminoLargo(arboles, Numerotope, origen, destino);
            caminoLargo.caminoLargo();
            Font fuente = new Font("Arial", Font.PLAIN, 14);
            txtDistancia.setFont(fuente);
            txtDistancia.setText("No hay ningun error :)");
            txtDistancia.setForeground(Color.BLUE);
            txtDistancia.setEnabled(false);
            
            txtDistancia.setText(caminoLargo.getAcumulado() + " KM");
        }
    }//GEN-LAST:event_btnCaminoLargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbicacionGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbicacionGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbicacionGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbicacionGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbicacionGrafos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaminoCorto;
    private javax.swing.JButton btnCaminoLargo;
    private javax.swing.JButton btnMostrarCaminos;
    private javax.swing.JComboBox<String> cbxEditorialesDestino;
    private javax.swing.JComboBox<String> cbxEditorialesOrigen;
    private javax.swing.JLabel imgMapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtDistancia;
    // End of variables declaration//GEN-END:variables
}
